api_platform:
    show_webby: false
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
        html: [ 'text/html' ]
        jsonhal: [ 'application/hal+json' ]

    swagger:
        api_keys:
            # overridden in OpenApiFactoryDecorator
            access_token:
                name: Authorization
                type: header

    defaults:
        extra_properties:
            standard_put: true


    # enable_docs: false
    # enable_entrypoint: false
    # enable_swagger: false
    # enable_swagger_ui: false
